### ISSUE TITLE
Fix pre-commit

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/plugin-extend-env#15]
https://results.pre-commit.ci/run/github/719497043/1702535043.3d-ZK0xPS7yn2voT2jW-LQ

Maybe @pat-s, do you know more?

**Comment by pat-s** [comment]
Looks like a temporary DL issue?

**Comment by pat-s** [comment]
I'm on the phone atm so can't do much browsing. But we use this hook in many repos, if it only fails here then it's likely a repo specific issue.

**Comment by pat-s** [comment]
It works locally with `pre-commit run --all-files` so the config seems ok. I don't see any other config issue either. It's a bit strange it failed for all tries in this repo so far.

But it reads and looks like a DL issue. I'd suggest observing a bit longer. The last run was 9 days ago, maybe things are better meanwhile.

**Comment by anbraten** [comment]
Check if I could reset any caches, but from what I saw there is no settings area, etc.

**Comment by pat-s** [comment]
Precommit uses a global cache for all runs for all users. I suspect it might be an issue with the DL of the `toolchain` pkg. I'll play around a bit

**Comment by pat-s** [comment]
Apparently a golang version of x.x.x doesn't work, only x.x
